# Generated by Django 3.0.5 on 2020-08-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softdeletemodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='softdeletemodel',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalSoftDeleteModel',
        ),
        migrations.DeleteModel(
            name='SoftDeleteModel',
        ),
    ]
