# Generated by Django 3.0.5 on 2020-07-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_historicalreminder_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='case',
            new_name='case_title',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='contract',
            new_name='contract_title',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='case',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='contract',
        ),
        migrations.AddField(
            model_name='expense',
            name='case_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Case'),
        ),
        migrations.AddField(
            model_name='expense',
            name='contract_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Contract'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='case_title',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lawyer.Case'),
        ),
        migrations.AddField(
            model_name='task',
            name='case_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Case'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.AccountUser'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='contract_title',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lawyer.Contract'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sender',
            field=models.ManyToManyField(blank=True, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Contract'),
        ),
    ]
