# Generated by Django 3.0.5 on 2020-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_auto_20200725_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
