# Generated by Django 3.0.5 on 2020-07-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lawyer', '0006_auto_20200726_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_upload',
            new_name='file_upload',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='document_upload',
            new_name='file_upload',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='document_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='document_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='brows_document',
        ),
        migrations.RemoveField(
            model_name='task',
            name='brows_document',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='lawyer.Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=40, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Account')),
                ('user_permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
