# Generated by Django 3.0.5 on 2020-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lawyer', '0007_auto_20200727_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='UserPermission',
        ),
    ]
