# Generated by Django 3.0.5 on 2020-07-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lawyer', '0008_auto_20200727_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='role',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user_permission',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'permissions': (('view_client', 'Can view client'),),
                'managed': False,
                'proxy': True,
                'default_permissions': (),
            },
            bases=('lawyer.baseuser',),
        ),
    ]
