# Generated by Django 3.0.5 on 2020-08-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0013_auto_20200804_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.Contract'),
        ),
    ]
