# Generated by Django 3.0.5 on 2020-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0014_auto_20200804_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
