# Generated by Django 3.0.5 on 2020-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0015_baseuser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Closed')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Closed')], default=1, null=True),
        ),
    ]
