# Generated by Django 3.0.5 on 2020-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0016_auto_20200805_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='task_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Pending'), (3, 'Done')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Pending'), (3, 'Done')], default=1, null=True),
        ),
    ]
