# Generated by Django 3.0.5 on 2020-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0017_auto_20200805_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('message_en', models.CharField(blank=True, max_length=200, null=True)),
                ('messag_ar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='documents',
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Closed')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open'), (2, 'Closed')], default=1, null=True),
        ),
    ]
