# Generated by Django 3.0.5 on 2020-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0018_auto_20200810_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalreminder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('Sent', 'Sent')], default='Paid', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('Sent', 'Sent')], default='Paid', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Paid', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Paid', max_length=12, null=True),
        ),
    ]
